/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToast: typeof import('./src/components/common/AppToast.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CategorySection: typeof import('./src/components/dashboard/CategorySection.vue')['default']
    CategorySections: typeof import('./src/components/dashboard/CategorySections.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Editor: typeof import('primevue/editor')['default']
    Galleria: typeof import('primevue/galleria')['default']
    IngredientCard: typeof import('./src/components/ingredient/IngredientCard.vue')['default']
    IngredientDetailDialog: typeof import('./src/components/ingredient/IngredientDetailDialog.vue')['default']
    IngredientGrid: typeof import('./src/components/ingredient/IngredientGrid.vue')['default']
    IngredientGroupSelector: typeof import('./src/components/ingredient/IngredientGroupSelector.vue')['default']
    IngredientList: typeof import('./src/components/ingredient/IngredientList.vue')['default']
    PageStateBlock: typeof import('./src/components/common/PageStateBlock.vue')['default']
    PopularRecipes: typeof import('./src/components/dashboard/PopularRecipes.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RecentViews: typeof import('./src/components/dashboard/RecentViews.vue')['default']
    RecipeCard: typeof import('./src/components/recipe/RecipeCard.vue')['default']
    RecipeComments: typeof import('./src/components/recipe/RecipeComments.vue')['default']
    RecipeDetailGallery: typeof import('./src/components/recipe/RecipeDetailGallery.vue')['default']
    RecipeDetailHeader: typeof import('./src/components/recipe/RecipeDetailHeader.vue')['default']
    RecipeDetailIngredients: typeof import('./src/components/recipe/RecipeDetailIngredients.vue')['default']
    RecipeDetailSteps: typeof import('./src/components/recipe/RecipeDetailSteps.vue')['default']
    RecipeFormBasicInfo: typeof import('./src/components/recipe/form/RecipeFormBasicInfo.vue')['default']
    RecipeFormClassification: typeof import('./src/components/recipe/form/RecipeFormClassification.vue')['default']
    RecipeFormIngredients: typeof import('./src/components/recipe/form/RecipeFormIngredients.vue')['default']
    RecipeFormSteps: typeof import('./src/components/recipe/form/RecipeFormSteps.vue')['default']
    RecipeGridCard: typeof import('./src/components/recipe/RecipeGridCard.vue')['default']
    RecipeListItem: typeof import('./src/components/recipe/RecipeListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTop: typeof import('./src/components/ScrollToTop.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SocialLoginButtons: typeof import('./src/components/SocialLoginButtons.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToastUiEditor: typeof import('./src/components/editor/ToastUiEditor.vue')['default']
    ToastUiViewer: typeof import('./src/components/editor/ToastUiViewer.vue')['default']
    TodayRecommendations: typeof import('./src/components/dashboard/TodayRecommendations.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
