spring:
  config:
    import: optional:classpath:application-common.yml
  application:
    name : user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/knusrae_db
    username: knusrae_user
    password: CookRecipes999!@#
  jpa:
    hibernate:
      ddl-auto: update # dev : update, prd : validate or none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083
