#!/usr/bin/env bash
# Secrets Manager(JSON 키-값) → .env 형식 파일 생성 (호스트에서만 실행).
# docker-compose env_file: 로 지정할 경로에 씁니다.
#
# 필요: aws CLI, jq, EC2 인스턴스 프로필(또는 동등 자격) + GetSecretValue 권한
#
# 사용 예 (EC2에서 compose 실행 디렉터리 기준):
#   SECRET_ID=knusrae/prod AWS_REGION=ap-northeast-2 OUTPUT_FILE=./.env.secrets ./fetch-secrets-to-env.sh
#
# 레포에서 infra/scripts 기준으로 루트에 쓰기:
#   OUTPUT_FILE="$(git rev-parse --show-toplevel)/.env.secrets" ./fetch-secrets-to-env.sh

set -euo pipefail

SECRET_ID="${SECRET_ID:-}"
AWS_REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-ap-northeast-2}}"
OUTPUT_FILE="${OUTPUT_FILE:-${SECRETS_ENV_FILE:-./.env.secrets}}"
FAIL_ON_INVALID_KEYS="${FAIL_ON_INVALID_KEYS:-1}"
VALUE_FORMAT="${VALUE_FORMAT:-json}" # json | raw

for cmd in aws jq; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "ERROR: '$cmd' 명령이 필요합니다. 설치 후 다시 실행하세요." >&2
    exit 1
  fi
done

if [[ -z "$SECRET_ID" ]]; then
  echo "ERROR: SECRET_ID가 비어 있습니다. 예: SECRET_ID=knusrae/prod" >&2
  exit 1
fi

tmp_json="$(mktemp)"
tmp_out="$(mktemp)"
cleanup() {
  rm -f "$tmp_json" "$tmp_out"
}
trap cleanup EXIT

aws secretsmanager get-secret-value \
  --secret-id "$SECRET_ID" \
  --region "$AWS_REGION" \
  --query SecretString \
  --output text >"$tmp_json"

# aws --output text 는 null/None일 때 "None"을 줄 수 있음 (Binary secret이면 SecretString이 없음)
if [[ "$(tr -d '[:space:]' <"$tmp_json")" == "None" ]] || [[ "$(tr -d '[:space:]' <"$tmp_json")" == "null" ]] || [[ ! -s "$tmp_json" ]]; then
  echo "ERROR: SecretString을 읽지 못했습니다. (Binary secret이거나 비어 있음) SECRET_ID=$SECRET_ID" >&2
  exit 1
fi

# SecretString이 비어 있거나 JSON이 아니면 여기서 실패
jq -e 'type == "object"' "$tmp_json" >/dev/null

invalid_keys="$(
  jq -r '
    to_entries[]
    | select(.key | test("^[A-Za-z_][A-Za-z0-9_]*$") | not)
    | .key
  ' "$tmp_json" | sort -u
)"
if [[ -n "$invalid_keys" ]]; then
  if [[ "$FAIL_ON_INVALID_KEYS" == "1" ]]; then
    echo "ERROR: .env 키 형식이 아닌 항목이 있습니다(FAIL_ON_INVALID_KEYS=1)." >&2
    echo "$invalid_keys" | sed 's/^/  - /' >&2
    exit 1
  fi
  echo "WARN: .env 키 형식이 아닌 항목을 제외합니다(FAIL_ON_INVALID_KEYS=0)." >&2
  echo "$invalid_keys" | sed 's/^/  - /' >&2
fi

{
  echo "# Generated by fetch-secrets-to-env.sh — do not commit. Secret: ${SECRET_ID}"
  # 평면 스칼라만 지원(중첩 객체/배열 키는 건너뜀). 값은 jq @json으로 이스케이프.
  if [[ "$VALUE_FORMAT" == "raw" ]]; then
    jq -r '
      to_entries[]
      | select(.key | test("^[A-Za-z_][A-Za-z0-9_]*$"))
      | select(
          .value != null
          and (.value | type) != "object"
          and (.value | type) != "array"
        )
      | "\(.key)=\(.value | tostring)"
    ' "$tmp_json"
  else
    jq -r '
      to_entries[]
      | select(.key | test("^[A-Za-z_][A-Za-z0-9_]*$"))
      | select(
          .value != null
          and (.value | type) != "object"
          and (.value | type) != "array"
        )
      | "\(.key)=\(.value | @json)"
    ' "$tmp_json"
  fi
} >"$tmp_out"

out_dir="$(dirname "$OUTPUT_FILE")"
mkdir -p "$out_dir"

tmp_final="${OUTPUT_FILE}.tmp.$$"
cp "$tmp_out" "$tmp_final"
chmod 600 "$tmp_final"
mv -f "$tmp_final" "$OUTPUT_FILE"

echo "Wrote $OUTPUT_FILE (mode 600). 다음: docker compose up -d (또는 재시작)"
